set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk [get_ports clk]

set_property PACKAGE_PIN U18 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property PACKAGE_PIN T18 [get_ports enable]
set_property IOSTANDARD LVCMOS33 [get_ports enable]

set_property PACKAGE_PIN V17 [get_ports {duty_a[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {duty_a[0]}]
set_property PACKAGE_PIN V16 [get_ports {duty_a[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {duty_a[1]}]
set_property PACKAGE_PIN W16 [get_ports {duty_a[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {duty_a[2]}]
set_property PACKAGE_PIN W17 [get_ports {duty_a[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {duty_a[3]}]
set_property PACKAGE_PIN W15 [get_ports {duty_a[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {duty_a[4]}]
set_property PACKAGE_PIN V15 [get_ports {duty_a[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {duty_a[5]}]
set_property PACKAGE_PIN W14 [get_ports {duty_a[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {duty_a[6]}]
set_property PACKAGE_PIN W13 [get_ports {duty_a[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {duty_a[7]}]

set_property PACKAGE_PIN A14 [get_ports pwm_a_h]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_a_h]
set_property PACKAGE_PIN A16 [get_ports pwm_a_l]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_a_l]
set_property PACKAGE_PIN B15 [get_ports pwm_b_h]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_b_h]
set_property PACKAGE_PIN B16 [get_ports pwm_b_l]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_b_l]
